### Product Index
GET http://localhost:3000/products


### Product Show
GET http://localhost:3000/products/1

### Product Create
POST http://localhost:3000/products/
Content-Type: application/json

{
  "name": "test name",
  "price": "test price",
  "description": "test description",
  "image_url": "test image_url"
}

### Product Update
PATCH http://localhost:3000/products/
Content-Type: application/json

### Product Destroy
DELETE http://localhost:3000/products/7

### Supplier Index
GET http://localhost:3000/suppliers

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Orders create
POST http://localhost:3000/orders
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "product_id": 2,
  "quantity": 1
}

### Orders show
GET http://localhost:3000/orders/1
Authorization: Bearer {{jwt}}

### Order Index
GET http://localhost:3000/orders/

